on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Version to build"
        required: true
          
name: Build and Push Workbench Daily Images
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:    
            - name: Check Out Repo at Triggered Branch
              uses: actions/checkout@v4
             
            - name: Get RSW Version
              id: get-version
              run: |
                VERSION=${{inputs.version}} 
                echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
                echo "TAG_VERSION=$(echo -n "$VERSION" | sed 's/+/-/g')" >> $GITHUB_OUTPUT
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            
            - name: Login to ghcr.io
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Build and Push r-session-complete
              uses: docker/build-push-action@v5
              with:
                context: ./r-session-complete
                push: true
                build-args: | 
                    RSW_VERSION=${{ steps.get-version.outputs.VERSION }}
                tags: |
                    ghcr.io/npelikan/pwb-session-daily-databricks:${{ steps.get-version.outputs.TAG_VERSION }}-ubuntu2204
                    ghcr.io/npelikan/pwb-session-daily-databricks:latest


              

            
