on: workflow_dispatch

name: Build and Push Rocky9 Workbench Daily Images
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check Out main Branch
              if: github.event.schedule == '0 8 * * *'
              uses: actions/checkout@v3
              with:
                ref: 'main'
      
            - name: Check Out Repo at Triggered Branch
              if: github.event.schedule != '0 8 * * *'
              uses: actions/checkout@v3
             
            - name: Get RSW Version
              id: get-version
              run: |
                VERSION=$(python tools/get-version.py workbench --type=daily --local)  
                echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
                echo "TAG_VERSION=$(echo -n "$VERSION" | sed 's/+/-/g')" >> $GITHUB_OUTPUT
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            
            - name: Login to ghcr.io
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Build and Push r-session-complete
              uses: docker/build-push-action@v5
              with:
                context: ./rl9/r-session-complete
                push: true
                build-args: | 
                    RSW_VERSION=${{ steps.get-version.outputs.VERSION }}
                tags: |
                    ghcr.io/npelikan/pwb-session-daily-rl9:${{ steps.get-version.outputs.TAG_VERSION }}
                    ghcr.io/npelikan/pwb-session-daily-rl9:latest


              

            
