on:
    schedule:
      # every morning at 8am UTC
      # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule
      # make sure to change the `if` commands below when changing the schedule
      - cron: '0 8 * * *'
    push:
      branches:
        - main
    pull_request:
name: Prerelease - Build and Push
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check Out main Branch
              if: github.event.schedule == '0 8 * * *'
              uses: actions/checkout@v3
              with:
                ref: 'main'
      
            - name: Check Out Repo at Triggered Branch
              if: github.event.schedule != '0 8 * * *'
              uses: actions/checkout@v3
             
            - name: Get RSW Version
              id: get-version
              run: |
                VERSION=$(python tools/get-version.py workbench --type=daily --local)  
                echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
                echo "TAG_VERSION=$(echo -n "$VERSION" | sed 's/+/-/g')" >> $GITHUB_OUTPUT
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            
            # Removed to save some run time
            # - name: Free Disk Space (Ubuntu)
            #   uses: jlumbroso/free-disk-space@v1.3.1
            #   with:
            #     tool-cache: false
            #     android: true
            #     dotnet: true
            #     haskell: true
            #     large-packages: true
            #     docker-images: true
            #     swap-storage: false
            
            - name: Login to ghcr.io
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            # - name: Build and push Rsession Pro
            #   run: |
            #     docker build -t ghcr.io/npelikan/product-base-pro:ubuntu2204-latest-py product-base-pro
            #     docker image push ghcr.io/npelikan/product-base-pro:ubuntu2204-latest-py
            
            - name: Build and Push r-session-complete
              uses: docker/build-push-action@v5
              with:
                context: ./r-session-complete
                push: true
                build-args: 
                    - RSW_VERSION=${{ steps.get-version.outputs.VERSION }}
                tags:
                    - ghcr.io/npelikan/r-session-complete:${{ steps.get-version.outputs.TAG_VERSION }}-ubuntu2204-latest-py
                    - ghcr.io/npelikan/pwb-session-daily:${{ steps.get-version.outputs.TAG_VERSION }}-ubuntu2204
                    - ghcr.io/npelikan/pwb-session-daily:latest

            # - name: Build and Push r-session-complete
            #   run: |
            #     docker pull ghcr.io/npelikan/product-base-pro:ubuntu2204-latest-py
            #     docker build \
            #         --build-arg RSW_VERSION=${{ steps.get-version.outputs.VERSION }} \
            #         -t ghcr.io/npelikan/r-session-complete:${{ steps.get-version.outputs.TAG_VERSION }}-ubuntu2204-latest-py \

            #         r-session-complete
            #     docker image push ghcr.io/npelikan/r-session-complete:${{ steps.get-version.outputs.TAG_VERSION }}-ubuntu2204-latest-py

              

            
