on: workflow_dispatch
jobs: 
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Check Out Repo at Triggered Branch
              uses: actions/checkout@v3
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            
            - name: Login to ghcr.io
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Build and Push al2023 base image
              uses: docker/build-push-action@v5
              with:
                  context: ./al2023/product-base-pro
                  push: true
                  tags: |
                    ghcr.io/npelikan/product-base-pro:al2023-latest
            
            - name: Get RSW Version
              id: get-version
              run: |
                VERSION=$(python tools/get-version.py workbench --type=daily --local)  
                echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
                echo "TAG_VERSION=$(echo -n "$VERSION" | sed 's/+/-/g')" >> $GITHUB_OUTPUT
            
            - name: Build and Push r-session-complete
              uses: docker/build-push-action@v5
              with:
                context: ./al2023/r-session-complete
                push: true
                build-args: | 
                    RSW_VERSION=${{ steps.get-version.outputs.TAG_VERSION }}
                tags: |
                    ghcr.io/npelikan/pwb-session-daily-al2023:${{ steps.get-version.outputs.TAG_VERSION }}
                    ghcr.io/npelikan/pwb-session-daily-al2023:latest
                
            
            